### ISSUE TITLE
config file not generating in data directory

### ISSUE THREAD

**Issue by adityapatn** [GreenhouseModding/enchantment-disable-tag#3]
I am playing on fabric 1.21 and installed enchantment disable tag. I have started minecraft and entered the world several times, and then looked for a config file to edit inside my minecraft folder. No such file is generated. I have tried putting the .jar in both the mods folder and the datapacks folder of my world. I would greatly appreciate any help.

**Comment by adityapatn** [comment]
@MerchantPug

**Comment by ChrysanthCow** [comment]
This mod does not use configs at all, it instead uses vanilla's datapack system, which will handle syncing and the sort for you. This also means that the mod can function serverside, without the client having anything other than the mod optionally.

To quote @UltrusBot from issue #1 

> This mod uses the vanilla tag system, so following the vanilla wiki on how to create a datapack [which is here](https://minecraft.wiki/w/Tutorials/Creating_a_data_pack#Tags) can be helpful.
> 
> The tag this mod adds functionality to is specifically would be `data/enchantmentdisabletag/tags/enchantment/disabled.json`

You would then place the datapack within your world's datapack folder, or if you are using a global datapack loading mod such as OpenLoader (recommended if you're making a modpack), you'd place it wherever that stores its datapacks.

**Comment by adityapatn** [comment]
I apologize, but I'm having trouble understanding how to add the tag to enchantments to disable them. After I have placed the datapack in [my world folder]/datapacks, what do I do? Is there a command to use it? Thanks for the help.

**Comment by GeaRetteX** [comment]
Hey, same issue here, can we get an example/template on how to use this? i just want to remove mending and unbreaking, how can i do that?

**Comment by adityapatn** [comment]
I spoke to the creator on Discord. I suggest you download the example datapack they have there. It didn't work for me, but my game was probably acting up. Put that in /datapacks/, then edit the disabled.json file. Reload the world and it should work (also make sure to enable the datapack)

**Comment by ChrysanthCow** [comment]
I'll be doing two things:

Linking an example datapack on the mod page, and also explaining how you use the tag system from zero knowledge in a writeup

**Comment by ChrysanthCow** [comment]
Hello! I've written up a write-up that should explain how EDT's tag works and how to make one from zero knowledge.

https://github.com/GreenhouseTeam/enchantment-disable-tag/wiki
