### ISSUE TITLE
[Suggestion] Enchantment levels

### ISSUE THREAD

**Issue by Saghik** [GreenhouseModding/enchantment-disable-tag#4]
Maybe it could also work with enchantment levels. I mean, certain levels of enchantment can be disabled.

**Comment by ChrysanthCow** [comment]
Hi, this would require a total rewrite to how the mod is formatted. It'd no longer be a simple datapack tag, but instead multiple tags/basically a config.


You're probably asking this from a 1.20.1 angle too, which I have pretty much wished to abandon for a while. 1.21's data driven enchantments pretty much support this by changing out the max level of the enchantment's JSON, so i feel a feature like this would be wasted at that point.

**Comment by Saghik** [comment]
Oh, ok. Thnx and sorry!
